 name: CI
 on:
   push:
 jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v5
      - name: Compile
        run: sbt compile
      - name: install surge
        run: sudo npm install --global surge
      - name: Deploythesurge
        run: sudo surge ./build design-pattern-by-waqas.surge.sh --token ${{ secrets.SURGE_TOKEN }}
